// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		// Variable initialization:
	    int n = Integer.parseInt(args[0]);
		int a = 0;
		int b = 0;
		// System.out.println("number of times: " + n);

		// Number generation:
		while (n > 0) {
			if (Math.random()>0.5) {
				a = a + 1;
			}
			else
				b = b + 1;
			n = n-1;
		}
		//Final print:
		System.out.println("> 0.5:  " + a + " times");
		System.out.println("<= 0.5:  " + b + " times");
		// Test before ratio calculation:
		if (Math.min(a, b) != 0) {
			System.out.println("Ratio: " + (double)Math.min(a, b)
			/Math.max(a, b));
		}

	}
}
